### ISSUE TITLE
Can't save changes. 

### ISSUE THREAD

**Issue by EricRLB** [cardoso/Rocket.Chat.ContentFilter#5]
I try to add expressions to the bot, but the save option is greyed out and I cant add anything.

**Comment by murray484** [comment]
@EricRLB  I'm having the same issue - how did you resolve it?

**Comment by EricRLB** [comment]
@murray484 I had to add a standard text entry (not a regex) and it would allow me to save it alongside any other regular expressions entered before it. I used "faceb00k.com" to provide an example.

**Comment by murray484** [comment]
Thanks! That worked for me too.

**Comment by cardoso** [comment]
Are y'all still able to use this App with the latest Rocket.Chat? If not, which version are you using? It's been a while since I've checked. (2 years)

**Comment by murray484** [comment]
I'm using it with 3.0.6 (I think that's the latest stable version) and it's working great aside from the save button being a bit finicky.

**Comment by cardoso** [comment]
That's surprising! Thanks. :)
